# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BikeAvailabilityApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

  # Pods for BikeAvailabilityApp

  target 'BikeAvailabilityAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BikeAvailabilityAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
